from manimlib import *
class Notice(VGroup):
    def __init__(self, m_text1, m_text2, **kwargs):

        super().__init__(**kwargs)
        self.line1 = Text(m_text1, font = 'simsun')
        self.line2 = Text(m_text2, font = 'simsun')
        if self.line1.get_height() < 0.5:
            self.line1.scale(1.25)
        if self.line2.get_height() < 0.5:
            self.line2.scale(1.25)
        self.line2.next_to(self.line1, DOWN)
        self.add(self.line1, self.line2)
        self.scale(0.5)
        self.shift(np.array([5.8,2.9,0]))#copy from yuezhengchuixing
class main(Scene):
    def construct(self):
        notice1=Notice("　华罗庚","请勿模仿")
        notice2=Notice("奇妙操作", "请　疑惑")
        notice3=Notice("中学内容","请　回忆")
        notice4=Notice("视频前言","请听介绍")
        notice5=Notice("简单部分","请　理解")
        notice6=Notice("不严谨处","请　思考")
#scene one start
        quote=Text("  新的数学方法和概念，常\n常比解决数学问题本身更重要。",font='simsun')
        author=Text("-华罗庚",color=YELLOW,font='msyh').next_to(quote.get_corner(DR), DL)
        self.wait(4)
        self.play(Write(quote),Write(notice1),runtime = 2)
        self.play(Write(author))
        self.wait(2)
        self.play(FadeOut(quote), FadeOut(author))
        self.wait(1)
#scene one end
#scene two start
        titlemain = Text(text="自然数幂和公式",font="msyh",gradient=[RED, ORANGE, YELLOW, GREEN, BLUE , PURPLE],font_size=100)
        titlesub =Text(text="对杨辉三角的一种理解",font="SimSun",Color=YELLOW).next_to(titlemain,DOWN)
        title =VGroup(titlesub,titlemain)
        text_show = TexText(r"""在中学课本的边边角角，我们可以发现这样的公式\\
            \begin{math} $\begin{flalign}
            \sum_{i=1}^{m}i^1&=\frac{(m+1)m}{2}\\
            \sum_{i=1}^{m}i^2&=\frac{m(m+1)(2m+1)}{6}\\
            \sum_{i=1}^{m}i^3&=\frac{m^2(m+1)(m+1)}{4}
            \end{flalign}$ \end{math}\\""",font_size=36).move_to(UP*1.5+LEFT)
        self.play(ReplacementTransform(notice1,notice4),Write(titlemain))
        self.wait(2)
        self.play(Write(titlesub))
        self.wait(2)
        self.play(FadeOut(title,UP))
        self.wait(2)
        self.play(Write(text_show),ReplacementTransform(notice4,notice3))
        self.wait(1.5)
        self.play(FadeOut(text_show,DOWN))
#scene two end
#scene three start
        text_1 =TexText(r"(1)的推导的简单方法就是倒序相加法",font_size=36,tex_to_color_map={"倒序相加法":YELLOW}).shift(LEFT*1+UP*2)
        text_1_1 =TexText(r"""\begin{math} $\begin{align*} S&=1+2+\cdots+(n-1)+n\\ S&=n+(n-1)+\cdots+2+1 \end{align*}$ \end{math}""").next_to(text_1,DOWN)
        text_1_2 =TexText(r"""\begin{math} $\begin{align*} 2S&=(n+1)+(n+1)+\cdots+(n+1)+(n+1)\\ S&=\frac{(n+1)n}{2} \end{align*}$ \end{math}""",font_size=36).next_to(text_1,DOWN)
        
        text_2=TexText(r"""(2)的得到的简单方法就是待定系数法\\ 设$S=a_1n^3+a_2n^2+a_3n$\\\begin{math} $\begin{align*} \begin{cases} 
            a_1+a_2+a_3=1\\ 8a_1+4a_2+2a_3=5\\ 27a_1+9a_2+3a_3=14 \end{cases} \end{align*}$ \end{math}""",font_size=36,tex_to_color_map={"待定系数法":RED}).shift(UP*1+LEFT*1)
        text_2_1=TexText(r"""\begin{flushleft} 解释：\\ 先有$(i+1)^k-i^k=C_K^1n^(k-1)+\cdots+1$\\ 累加$(n+1)^k-1=C_k^1\sum_{i=1}^{n}i^(k-1)+\cdots+1$\\ 再逐级递推\end{flushleft}""",font_size=36,Color=YELLOW).shift(UP*1+LEFT*1)
        self.play(Write(text_1),ReplacementTransform(notice3,notice5))
        self.wait()
        self.play(ShowCreation(text_1_1))
        self.wait()
        self.play(FadeTransform(text_1_1,text_1_2))
        self.wait(2)
        self.remove(text_1,text_1_2)
        self.play(ShowCreation(text_2))
        self.wait(4)
        self.play(FadeTransform(text_2,text_2_1,rumtime=2),ReplacementTransform(notice5,notice6))
        self.wait(4)
        self.play(FadeOutToPoint(text_2_1,(0,0,0)))
#scene three end
        text_3=TexText(r"""下面是一个数组\\$\ \ 1\ \ 4\ 10\ 20$\\$\ \ 1\ \ 3\ \ 6\ 10$\\$\ \ 1\ \ 2\ \ 3\ \ 4$\\$\ \ 1\ \ 1\ \ 1\ \ 1$\\""",font_size=36).shift(UP*1+LEFT*1)
        text_3sub=TexText(r"""满足:$N(x+1,y+1)=N(x+1,y)+N(x,y+1)$\\也就是$N(x+1,y+1)=\sum_{i=1}^{y+1}N(x,i+1)$\\""",
            tex_to_color_map={"$N(x+1,y+1)N(x+1,y)+N(x,y+1)$":GREEN,"$N(x+1,y+1)=\sum_{i=1}^{y+1}N(x,i+1)$":GREEN},font_size=36).next_to(text_3,DOWN)
        text_3_1=TexText(r"""这与组合数的性质$C_m^n=C_{m-1}^n+C_{m-1}^{n-1}$类似""",tex_to_color_map={"$C_m^n=C_{m-1}^n+C_{m-1}^{n-1}$":YELLOW},font_size=36).next_to(text_3sub,DOWN) 
        text_3_2=TexText(r"""数组变换\\$\ \ 0\ \ 0\ \ 0\ \ 1$\\$\ \ 0\ \ 0\ \ 1\ \ 3$\\$\ \ 0\ \ 1\ \ 2\ \ 3$\\$\ \ 1\ \ 1\ \ 1\ \ 1$\\""",font_size=36).shift(UP*1+LEFT*1)
        text_3_3=TexText(r"奇妙的变换:出现0和变换过程",font_size=36,tex_to_color_map={"出现0":YELLOW,"变换过程":YELLOW}).next_to(text_3_2,DOWN)
        self.play(ReplacementTransform(notice6,notice2),Write(text_3),Write(text_3sub))
        self.wait(2)
        self.play(Write(text_3_1))
        self.wait(3)
        self.play(FadeOut(text_3_1,DOWN),FadeOut(text_3sub,DOWN))
        self.wait(3)
        self.play(ReplacementTransform(text_3,text_3_2,runtime=2))
        self.wait(3)
        self.play(Write(text_3_3))
        self.play(FadeOutToPoint(text_3_2,[0,0,0]),FadeOutToPoint(text_3_3,[0,0,0]))
#scene three end 
#scene four start 
        text_4=TexText(r"""\begin{flushleft}\ \ 解释：\\出现0满足:$N(x+1,y+1)=N(x+1,y)+N(x,y+1)$\\变换过程：从下起第a行向右移动(a-1)\\\end{flushleft}""",font_size=36).shift(UL)
        text_4_1=TexText(r"""特别地，这也是杨辉三角变来的\\""",font_size=36)
        text_4_2=TexText(r"""$\ \ \ 1 $\\$\ \ 1 \ $\\$\ 1 \ 3 $\\$1 \ 2 \ $\\$\ 1 \ 3 $\\$\ \ 1 \ $\\$\ \ \ 1 $""").shift(RIGHT)
        text_4_3=TexText(r"""$\ \ \ 1 $\\$\ \ \ \ $\\$\ \ 1 3 $\\$\ \ \ \ $\\$\ 1 2 3 $\\$\ \ \ \ $\\$1 1 1 1 $""").shift(LEFT)
        text_4g=VGroup(text_4_3,text_4_2)
        text_4_4=TexText(r"""这也解释了数组和组合数的关系""").next_to(text_4g,DOWN)
        self.play(Write(text_4),ReplacementTransform(notice2,notice6))
        self.wait(2)
        self.play(Write(text_4_1))
        self.wait(2)
        self.play(FadeOut(text_4,DOWN),FadeOut(text_4_1,DOWN))
        self.play(FadeInFromPoint(text_4_3,[-1,0,0]),ReplacementTransform(notice6,notice2))
        self.play(FadeIn(text_4_2,RIGHT))
        self.wait(4)
        self.play(Write(text_4_4))
        self.wait(3)
        self.play(Uncreate(text_4g))
        self.play(Uncreate(text_4_4))
#scene four end
#scene five start
        text_5=TexText(r"""谈到组合数,如何解释$y>x,C_x^y=0$呢?""",tex_to_color_map={"$y>x,C_x^y=0$":YELLOW},font_size=36).shift(UP*1)
        text_5sub=TexText(r"""解释是$C_x^y=\frac{x(x-1)\cdots(x-y+1)}{y!}$,$y>x会出现0$""",font_size=36).next_to(text_5,DOWN)
        text_5_1=TexText(r"""那么第二象限的值呢？""",tex_to_color_map={"第二象限？":RED},font_size=36).next_to(text_5sub,DOWN)
        text_5_2=TexText(r"""$\ \ 0\ \ 0\ \ 0\ \ 1$\\$\ \ 0\ \ 0\ \ 1\ \ 3$\\$\ \ 0\ \ 1\ \ 2\ \ 3$\\$\ \ 1\ \ 1\ \ 1\ \ 1$\\""",font_size=36)
        text_5_3=TexText(r"""$-4\ -1\ 0\ 0\ 0\ 1$\\$3\ 1\ 0\ 0\ 1\ 3$\\$-2\ -1\ 0\ 1\ 2\ 3$\\$1\ 1\ 1\ 1\ 1\ 1$""",font_size=36)
        text_5_4=TexText(r"负数如何解释呢？",color=RED).next_to(text_5_3,DOWN)
        text_5_5=TexText(r"""第一种理解：二项式定理,$(1+x)^n$中$x^n$项系数\\第二种理解，$(1+x)^n$在$x=0$处泰勒展开中$x^n$项系数(猜的)""",font_size=36)
        self.play(Write(text_5),ReplacementTransform(notice2,notice6))
        self.wait(3)
        self.play(Write(text_5sub))
        self.wait(3)
        self.play(Write(text_5_1))
        self.wait(3)
        self.play(FadeOut(text_5,DOWN),FadeOut(text_5sub,DOWN),FadeOut(text_5_1,DOWN))
        self.wait(2)
        self.play(ShowCreation(text_5_2),ReplacementTransform(notice6,notice2))
        self.wait(2)
        self.play(ReplacementTransform(text_5_2,text_5_3))
        self.play(Write(text_5_4))
        self.play(FadeOut(text_5_3,DOWN),FadeOut(text_5_4,DOWN))
        self.wait(2)
        self.play(Write(text_5_5),ReplacementTransform(notice2,notice6))
        self.wait(4)
        self.play(Uncreate(text_5_5))
#scene five end
#scene six start
        text_6=TexText(r"""回到组合数的性质，可以得到组合数求和公式\\因此，只要把自然数幂表示为组合数的线性组合即可""",font_size=36)
        text_6_1=TexText(r"""以$n^2$为例：\\$-1\ 0\ 0\ 1$\\$1\ 0\ 1\ 4$\\$-1\ 1\ 3\ 5$\\$2\ 2\ 2\ 2$""",font_size=36)
        text_6_2=TexText(r"""\ 2为$C_{n+1}^2$系数\\-1为$C_n^1$系数""",font_size=36).next_to(text_6_1,DOWN)
        self.play(Write(text_6),ReplacementTransform(notice6,notice2))
        self.wait(4)
        self.play(FadeOutToPoint(text_6,[0,0,0]))
        self.play(FadeInFromPoint(text_6_1,[0,0,0]))
        self.wait(4)
        self.play(Write(text_6_2))
        self.wait(4)
        self.play(Uncreate(text_6_1),Uncreate(text_6_2))
#scene six end
#scene seven start
        text_7=TexText(r"""线性组合也可以看成两个数组相加""",font_size=64,Color=YELLOW)
        text_7_1=TexText(r"""$0\ 0\ 1$\\$0\ 1\ 4$\\$1\ 3\ 5$\\$2\ 2\ 2$""",font_size=36).shift(UP*1)
        text_7_2=TexText(r"""$0\ 0\ 0$\\$0\ 0\ 1$\\$0\ 1\ 2$\\$1\ 1\ 1$""",font_size=36).shift(RIGHT*2+UP*1)
        text_7_3=TexText(r"""$0\ 0\ 1$\\$0\ 1\ 3$\\$1\ 2\ 3$\\$1\ 1\ 1$""",font_size=36).shift(LEFT*2+UP*1)
        text_7_4=TexText(r"""新数组为$(1+x)^n+(1+x)^{n-1}$的系数数组""",Color=RED,font_size=36).next_to(text_7,DOWN)
        text_7_5=TexText(r"""因此$S=C_{n+2}^3+C_{n+1}^3$""",font_size=36,Color=RED).next_to(text_7_4,DOWN)
        self.play(Write(text_7))  
        self.wait(4)
        self.play(Uncreate(text_7))
        self.play(Write(text_7_2),Write(text_7_3))
        self.wait(4)
        text_7v=VGroup(text_7_3,text_7_2)
        self.play(ReplacementTransform(text_7v,text_7_1))
        self.wait(4)
        self.play(Write(text_7_4)) 
        self.wait(5)        
        self.play(Write(text_7_5)) 
        self.wait(4)
        self.play(FadeOutToPoint(text_7_1,[0,0,0]),FadeOutToPoint(text_7_4,[0,0,0]),FadeOutToPoint(text_7_5,[0,1,0]),Uncreate(notice2))
        self.wait(4)